# Application name
spring.application.name=Make-My-Trip-service

# Config Server
spring.config.import=configserver:http://localhost:9191

# Service port
server.port=7777

# Admin Server
spring.boot.admin.client.enabled=true
spring.boot.admin.client.url=http://localhost:1111
management.endpoints.web.exposure.include=*

# Zipkin / Sleuth Tracing
management.tracing.enabled=false
management.zipkin.enabled=false

spring.zipkin.base-url=http://localhost:9412
spring.sleuth.sampler.probability=1.0

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.use-management-port=false